/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TerraCraft */

#ifndef _Included_TerraCraft
#define _Included_TerraCraft
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TerraCraft
 * Method:    setup
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TerraCraft_setup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
