/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class terracraft_TerraCraft */

#ifndef _Included_terracraft_TerraCraft
#define _Included_terracraft_TerraCraft
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     terracraft_TerraCraft
 * Method:    setup
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_terracraft_TerraCraft_setup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
