/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */



plugins {
    // Apply the java plugin to add support for Java
    java
    // Apply the application plugin to add support for building a CLI application.
    application
}


application {
    mainClass.set("terracraft.TerraCraft")
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "terracraft.TerraCraft"
    }
}


// do the equivalent to javac -h . TerraCraft.java
tasks.withType<JavaCompile> {
    options.headerOutputDirectory.set(file("src/main/java/terracraft"))
    options.compilerArgs.add("-h")
    options.compilerArgs.add("src/main/java/terracraft")
}